# Generated by Django 5.1.7 on 2025-03-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_claim_service_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-failure_date']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['date_shipment']},
        ),
        migrations.AlterModelOptions(
            name='technicalservice',
            options={'ordering': ['date']},
        ),
    ]
